name: medical_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.2
  get_storage: ^2.1.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  local_auth: ^2.3.0
  google_fonts: ^6.2.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/First Screen.png
    - assets/images/Group 93.png

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/font/LeagueSpartan-Light.ttf
          weight: 300
        - asset: assets/font/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/font/LeagueSpartan-Regular.ttf
          weight: 400
        - asset: assets/font/LeagueSpartan-SemiBold.ttf
          weight: 600
        - asset: assets/font/LeagueSpartan-Thin.ttf
          weight: 100
