// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATJaenUavjGeiYXz0Z-tS8ztsM0lDS_c4',
    appId: '1:624199765847:web:d526e3279cce30bcf43812',
    messagingSenderId: '624199765847',
    projectId: 'medical-app-da1d2',
    authDomain: 'medical-app-da1d2.firebaseapp.com',
    storageBucket: 'medical-app-da1d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZI2jbIDL5T-sPszcX8_egVddZnzL8Ro8',
    appId: '1:624199765847:android:f337ba2d2af94888f43812',
    messagingSenderId: '624199765847',
    projectId: 'medical-app-da1d2',
    storageBucket: 'medical-app-da1d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpRTIbOGwAHKLn4mDH3wTq5DTjPVj0y7s',
    appId: '1:624199765847:ios:b50a1acb87442a78f43812',
    messagingSenderId: '624199765847',
    projectId: 'medical-app-da1d2',
    storageBucket: 'medical-app-da1d2.appspot.com',
    iosClientId: '624199765847-kg7u0toocd21bpjiu3kn8kc6crtrb73h.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpRTIbOGwAHKLn4mDH3wTq5DTjPVj0y7s',
    appId: '1:624199765847:ios:b50a1acb87442a78f43812',
    messagingSenderId: '624199765847',
    projectId: 'medical-app-da1d2',
    storageBucket: 'medical-app-da1d2.appspot.com',
    iosClientId: '624199765847-kg7u0toocd21bpjiu3kn8kc6crtrb73h.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATJaenUavjGeiYXz0Z-tS8ztsM0lDS_c4',
    appId: '1:624199765847:web:4c01cf705cc5b81ff43812',
    messagingSenderId: '624199765847',
    projectId: 'medical-app-da1d2',
    authDomain: 'medical-app-da1d2.firebaseapp.com',
    storageBucket: 'medical-app-da1d2.appspot.com',
  );
}
